services:
  mysql_db:
    image: mysql:8
    container_name: mysql_picpay

    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: PicPayDB
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8282:8080"
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge
